### ISSUE TITLE
RA Error when trying to replace a room

### ISSUE THREAD

**Issue by LaFesta1749** [FakeMan2332/MERRoomReplacement#9]
Hello @FakeMan2332 ,
I'm trying to replace EzCafeteria room with schematic name EntranceCafeteria but it drops an error in RA console:

![image](https://github.com/FakeMan2332/MERRoomReplacement/assets/1494298/cf50e9ab-492a-49fa-974f-3c77884acb38)

Can you please help me fix it?
I have .* permissions so that is not the issue.
Also I tried with the config but nothing happens when I join the server and go to EzCafeteria room:
```
room_replacement:
# Indicates plugin enabled or not
  is_enabled: true
  # Indicates debug mode enabled or not
  debug: false
  # Options for replacement
  replacement_options:
  -
  # Indicates replacement is enabled or not
    is_enabled: true
    # Room for replacement
    target_room_type: EzCafeteria
    # Schematic that will be used
    schematic_name: 'EntranceCafeteria'
    # Chance for replace room with described schematic
    spawn_chance: 100
    position_offset:
      x: 0
      y: 0
      z: 0
    rotation_offset:
      x: 0
      y: 0
      z: 0
```

**Comment by FakeMan2332** [comment]
Hi! Sorry for long-time answer. Please read up the README file.
You can replace ONLY Lcz330 and HczTestRoom
